const { Webhook } = require('discord-webhook-node');
// require('dotenv').config();
// const url =  process.env.DiscordWebhook;
// const url_user =  process.env.DiscordWebhook_ZaloUserID;
var hook = null;
// const Log = require('./LogReport');

async function registerDiscordWebhook(url_user)
{
    this.hook = new Webhook(url_user);
}
async function DiscordWebhook(proxyUsed,user,pass,region,phone,otp)
{
    if(this.hook != null)
    {
        this.hook.success('**SUCCESS**', "Account Generated by Gabut_Tools",
        "Account : ||"+await user+":"+await pass+"||\nRegion : "+await region+"\nPhone : ||"+await phone+"\nOTP : ||"+await otp+"||\n Proxy Used : "+await proxyUsed);
    }
}
module.exports ={ DiscordWebhook,registerDiscordWebhook};