const { Webhook } = require('discord-webhook-node');
// require('dotenv').config();
// const url =  process.env.DiscordWebhook;
// const url_user =  process.env.DiscordWebhook_ZaloUserID;
var hook ;
// const Log = require('./LogReport');

async function registerDiscordWebhook(url_user)
{
    hook = new Webhook(url_user);
}
async function DiscordWebhook(proxyUsed,user,pass,region,phone)
{
    hook.success('**SUCCESS**', "Account Generated by Gabut_Tools",
    "Account : ||"+await user+":"+await pass+"||\nRegion : "+await region+"\nPhone : ||"+await phone+"||\n Proxy Used : "+await proxyUsed);
}
module.exports ={ DiscordWebhook,registerDiscordWebhook};